// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appendentry_request.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	appendentry_request.proto
	log_entry.proto
	vote_request.proto

It has these top-level messages:
	AppendEntriesReuqest
	AppendEntriesResponse
	LogEntry
	VoteRequest
	VoteResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type AppendEntriesReuqest struct {
	Term              uint64      `protobuf:"varint,1,opt,name=Term" json:"Term,omitempty"`
	FirstLogIndex     uint64      `protobuf:"varint,2,opt,name=FirstLogIndex" json:"FirstLogIndex,omitempty"`
	PreLogIndex       uint64      `protobuf:"varint,3,opt,name=PreLogIndex" json:"PreLogIndex,omitempty"`
	PreLogTerm        uint64      `protobuf:"varint,4,opt,name=PreLogTerm" json:"PreLogTerm,omitempty"`
	CommitIndex       uint64      `protobuf:"varint,5,opt,name=CommitIndex" json:"CommitIndex,omitempty"`
	HeartbeatInterval uint64      `protobuf:"varint,6,opt,name=HeartbeatInterval" json:"HeartbeatInterval,omitempty"`
	LeaderName        string      `protobuf:"bytes,7,opt,name=LeaderName" json:"LeaderName,omitempty"`
	LeaderHost        string      `protobuf:"bytes,8,opt,name=LeaderHost" json:"LeaderHost,omitempty"`
	LeaderExHost      string      `protobuf:"bytes,9,opt,name=LeaderExHost" json:"LeaderExHost,omitempty"`
	Entries           []*LogEntry `protobuf:"bytes,10,rep,name=Entries" json:"Entries,omitempty"`
}

func (m *AppendEntriesReuqest) Reset()                    { *m = AppendEntriesReuqest{} }
func (m *AppendEntriesReuqest) String() string            { return proto1.CompactTextString(m) }
func (*AppendEntriesReuqest) ProtoMessage()               {}
func (*AppendEntriesReuqest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AppendEntriesReuqest) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesReuqest) GetFirstLogIndex() uint64 {
	if m != nil {
		return m.FirstLogIndex
	}
	return 0
}

func (m *AppendEntriesReuqest) GetPreLogIndex() uint64 {
	if m != nil {
		return m.PreLogIndex
	}
	return 0
}

func (m *AppendEntriesReuqest) GetPreLogTerm() uint64 {
	if m != nil {
		return m.PreLogTerm
	}
	return 0
}

func (m *AppendEntriesReuqest) GetCommitIndex() uint64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func (m *AppendEntriesReuqest) GetHeartbeatInterval() uint64 {
	if m != nil {
		return m.HeartbeatInterval
	}
	return 0
}

func (m *AppendEntriesReuqest) GetLeaderName() string {
	if m != nil {
		return m.LeaderName
	}
	return ""
}

func (m *AppendEntriesReuqest) GetLeaderHost() string {
	if m != nil {
		return m.LeaderHost
	}
	return ""
}

func (m *AppendEntriesReuqest) GetLeaderExHost() string {
	if m != nil {
		return m.LeaderExHost
	}
	return ""
}

func (m *AppendEntriesReuqest) GetEntries() []*LogEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type AppendEntriesResponse struct {
	Success     bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	Term        uint64 `protobuf:"varint,2,opt,name=Term" json:"Term,omitempty"`
	Index       uint64 `protobuf:"varint,3,opt,name=Index" json:"Index,omitempty"`
	CommitIndex uint64 `protobuf:"varint,4,opt,name=CommitIndex" json:"CommitIndex,omitempty"`
}

func (m *AppendEntriesResponse) Reset()                    { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string            { return proto1.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()               {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AppendEntriesResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AppendEntriesResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendEntriesResponse) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *AppendEntriesResponse) GetCommitIndex() uint64 {
	if m != nil {
		return m.CommitIndex
	}
	return 0
}

func init() {
	proto1.RegisterType((*AppendEntriesReuqest)(nil), "proto.AppendEntriesReuqest")
	proto1.RegisterType((*AppendEntriesResponse)(nil), "proto.AppendEntriesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AppendEntries service

type AppendEntriesClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesReuqest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
}

type appendEntriesClient struct {
	cc *grpc.ClientConn
}

func NewAppendEntriesClient(cc *grpc.ClientConn) AppendEntriesClient {
	return &appendEntriesClient{cc}
}

func (c *appendEntriesClient) AppendEntries(ctx context.Context, in *AppendEntriesReuqest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := grpc.Invoke(ctx, "/proto.AppendEntries/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AppendEntries service

type AppendEntriesServer interface {
	AppendEntries(context.Context, *AppendEntriesReuqest) (*AppendEntriesResponse, error)
}

func RegisterAppendEntriesServer(s *grpc.Server, srv AppendEntriesServer) {
	s.RegisterService(&_AppendEntries_serviceDesc, srv)
}

func _AppendEntries_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesReuqest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppendEntriesServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AppendEntries/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppendEntriesServer).AppendEntries(ctx, req.(*AppendEntriesReuqest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppendEntries_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AppendEntries",
	HandlerType: (*AppendEntriesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _AppendEntries_AppendEntries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appendentry_request.proto",
}

func init() { proto1.RegisterFile("appendentry_request.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdd, 0x6a, 0xfa, 0x40,
	0x10, 0xc5, 0xff, 0x6a, 0xe2, 0xc7, 0xf8, 0x17, 0xe9, 0x62, 0x61, 0x6b, 0x4b, 0x09, 0xa1, 0x17,
	0x16, 0x8a, 0x17, 0xf6, 0x09, 0x4a, 0xb1, 0x28, 0x84, 0x52, 0xd2, 0xde, 0x16, 0x89, 0x3a, 0x88,
	0x60, 0x76, 0xe3, 0xee, 0x5a, 0xf4, 0xa2, 0x0f, 0xdd, 0x37, 0x28, 0x99, 0x55, 0xbb, 0x7e, 0x5c,
	0x25, 0x73, 0x7e, 0x27, 0x33, 0xd9, 0x33, 0x0b, 0x57, 0x49, 0x96, 0xa1, 0x98, 0xa2, 0x30, 0x6a,
	0x33, 0x52, 0xb8, 0x5c, 0xa1, 0x36, 0xdd, 0x4c, 0x49, 0x23, 0x99, 0x4f, 0x8f, 0x76, 0x73, 0x21,
	0x67, 0x23, 0xe2, 0x56, 0x0f, 0x7f, 0x8a, 0xd0, 0x7a, 0xa2, 0xaf, 0xfa, 0xc2, 0xa8, 0x39, 0xea,
	0x18, 0x57, 0x4b, 0xd4, 0x86, 0x31, 0xf0, 0x3e, 0x50, 0xa5, 0xbc, 0x10, 0x14, 0x3a, 0x5e, 0x4c,
	0xef, 0xec, 0x0e, 0x1a, 0x2f, 0x73, 0xa5, 0x4d, 0x24, 0x67, 0x43, 0x31, 0xc5, 0x35, 0x2f, 0x12,
	0x3c, 0x14, 0x59, 0x00, 0xf5, 0x37, 0x85, 0x7b, 0x4f, 0x89, 0x3c, 0xae, 0xc4, 0x6e, 0x01, 0x6c,
	0x49, 0x13, 0x3c, 0x32, 0x38, 0x4a, 0xde, 0xe1, 0x59, 0xa6, 0xe9, 0xdc, 0xd8, 0x0e, 0xbe, 0xed,
	0xe0, 0x48, 0xec, 0x01, 0x2e, 0x06, 0x98, 0x28, 0x33, 0xc6, 0xc4, 0x0c, 0x85, 0x41, 0xf5, 0x95,
	0x2c, 0x78, 0x99, 0x7c, 0xa7, 0x20, 0x9f, 0x17, 0x61, 0x32, 0x45, 0xf5, 0x9a, 0xa4, 0xc8, 0x2b,
	0x41, 0xa1, 0x53, 0x8b, 0x1d, 0xe5, 0x8f, 0x0f, 0xa4, 0x36, 0xbc, 0xea, 0xf2, 0x5c, 0x61, 0x21,
	0xfc, 0xb7, 0x55, 0x7f, 0x4d, 0x8e, 0x1a, 0x39, 0x0e, 0x34, 0x76, 0x0f, 0x95, 0x6d, 0x82, 0x1c,
	0x82, 0x52, 0xa7, 0xde, 0x6b, 0xda, 0x84, 0xbb, 0x91, 0x9c, 0xe5, 0x60, 0x13, 0xef, 0x78, 0xf8,
	0x0d, 0x97, 0x47, 0x91, 0xeb, 0x4c, 0x0a, 0x8d, 0x8c, 0x43, 0xe5, 0x7d, 0x35, 0x99, 0xa0, 0xd6,
	0x14, 0x7b, 0x35, 0xde, 0x95, 0xfb, 0x6d, 0x14, 0x9d, 0x6d, 0xb4, 0xc0, 0x77, 0x13, 0xf6, 0xf7,
	0xe9, 0xbb, 0xd9, 0x79, 0x27, 0xd9, 0xf5, 0x3e, 0xa1, 0x71, 0x30, 0x9e, 0x45, 0xc7, 0xc2, 0xf5,
	0xf6, 0xd7, 0xcf, 0x5d, 0x8c, 0xf6, 0xcd, 0x79, 0x68, 0x8f, 0x10, 0xfe, 0x1b, 0x97, 0x09, 0x3f,
	0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x46, 0x58, 0x9d, 0x44, 0x8d, 0x02, 0x00, 0x00,
}
