// Code generated by protoc-gen-go. DO NOT EDIT.
// source: svrbootstrap.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PreJoinRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Host   string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Client string `protobuf:"bytes,3,opt,name=client" json:"client,omitempty"`
}

func (m *PreJoinRequest) Reset()                    { *m = PreJoinRequest{} }
func (m *PreJoinRequest) String() string            { return proto1.CompactTextString(m) }
func (*PreJoinRequest) ProtoMessage()               {}
func (*PreJoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *PreJoinRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PreJoinRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PreJoinRequest) GetClient() string {
	if m != nil {
		return m.Client
	}
	return ""
}

type PreJoinResponse struct {
	Result     int64             `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Bootexpect int64             `protobuf:"varint,2,opt,name=bootexpect" json:"bootexpect,omitempty"`
	Message    string            `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Curnodes   map[string]string `protobuf:"bytes,4,rep,name=curnodes" json:"curnodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PreJoinResponse) Reset()                    { *m = PreJoinResponse{} }
func (m *PreJoinResponse) String() string            { return proto1.CompactTextString(m) }
func (*PreJoinResponse) ProtoMessage()               {}
func (*PreJoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *PreJoinResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *PreJoinResponse) GetBootexpect() int64 {
	if m != nil {
		return m.Bootexpect
	}
	return 0
}

func (m *PreJoinResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *PreJoinResponse) GetCurnodes() map[string]string {
	if m != nil {
		return m.Curnodes
	}
	return nil
}

func init() {
	proto1.RegisterType((*PreJoinRequest)(nil), "proto.PreJoinRequest")
	proto1.RegisterType((*PreJoinResponse)(nil), "proto.PreJoinResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DiscoveryAsBoot service

type DiscoveryAsBootClient interface {
	PreJoin(ctx context.Context, in *PreJoinRequest, opts ...grpc.CallOption) (*PreJoinResponse, error)
}

type discoveryAsBootClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryAsBootClient(cc *grpc.ClientConn) DiscoveryAsBootClient {
	return &discoveryAsBootClient{cc}
}

func (c *discoveryAsBootClient) PreJoin(ctx context.Context, in *PreJoinRequest, opts ...grpc.CallOption) (*PreJoinResponse, error) {
	out := new(PreJoinResponse)
	err := grpc.Invoke(ctx, "/proto.DiscoveryAsBoot/PreJoin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DiscoveryAsBoot service

type DiscoveryAsBootServer interface {
	PreJoin(context.Context, *PreJoinRequest) (*PreJoinResponse, error)
}

func RegisterDiscoveryAsBootServer(s *grpc.Server, srv DiscoveryAsBootServer) {
	s.RegisterService(&_DiscoveryAsBoot_serviceDesc, srv)
}

func _DiscoveryAsBoot_PreJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryAsBootServer).PreJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DiscoveryAsBoot/PreJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryAsBootServer).PreJoin(ctx, req.(*PreJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscoveryAsBoot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DiscoveryAsBoot",
	HandlerType: (*DiscoveryAsBootServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreJoin",
			Handler:    _DiscoveryAsBoot_PreJoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svrbootstrap.proto",
}

func init() { proto1.RegisterFile("svrbootstrap.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x36, 0x4d, 0x7f, 0x74, 0x44, 0x2b, 0x83, 0x96, 0xd0, 0x83, 0x94, 0xe0, 0xa1, 0xa7, 0x1c,
	0xea, 0x45, 0xea, 0xc5, 0xdf, 0x8b, 0x20, 0x94, 0xbc, 0x41, 0x1a, 0x07, 0x0d, 0xa6, 0x3b, 0x71,
	0x67, 0x13, 0xcc, 0xeb, 0xfa, 0x24, 0xb2, 0x9b, 0xb5, 0x68, 0xf1, 0x94, 0xf9, 0xbe, 0x99, 0x7c,
	0x3f, 0x0b, 0x28, 0x8d, 0x5e, 0x33, 0x1b, 0x31, 0x3a, 0xab, 0x92, 0x4a, 0xb3, 0x61, 0x1c, 0xb8,
	0x4f, 0xbc, 0x82, 0xe3, 0x95, 0xa6, 0x27, 0x2e, 0x54, 0x4a, 0x1f, 0x35, 0x89, 0x41, 0x84, 0xbe,
	0xca, 0x36, 0x14, 0x05, 0xb3, 0x60, 0x7e, 0x90, 0xba, 0xd9, 0x72, 0x6f, 0x2c, 0x26, 0xea, 0x75,
	0x9c, 0x9d, 0x71, 0x02, 0xc3, 0xbc, 0x2c, 0x48, 0x99, 0x28, 0x74, 0xac, 0x47, 0xf1, 0x57, 0x00,
	0xe3, 0xad, 0xa4, 0x54, 0xac, 0x84, 0xec, 0xad, 0x26, 0xa9, 0x4b, 0xe3, 0x54, 0xc3, 0xd4, 0x23,
	0x3c, 0x07, 0xb0, 0xb9, 0xe8, 0xb3, 0xa2, 0xbc, 0x53, 0x0f, 0xd3, 0x5f, 0x0c, 0x46, 0x30, 0xda,
	0x90, 0x48, 0xf6, 0x4a, 0xde, 0xe4, 0x07, 0xe2, 0x0d, 0xec, 0xe7, 0xb5, 0x56, 0xfc, 0x42, 0x12,
	0xf5, 0x67, 0xe1, 0xfc, 0x70, 0x71, 0xd1, 0x15, 0x4b, 0x76, 0xbc, 0x93, 0x7b, 0x7f, 0xf6, 0xa8,
	0x8c, 0x6e, 0xd3, 0xed, 0x5f, 0xd3, 0x6b, 0x38, 0xfa, 0xb3, 0xc2, 0x13, 0x08, 0xdf, 0xa9, 0xf5,
	0xbd, 0xed, 0x88, 0xa7, 0x30, 0x68, 0xb2, 0xb2, 0x26, 0xdf, 0xbb, 0x03, 0xcb, 0xde, 0x55, 0xb0,
	0x78, 0x86, 0xf1, 0x43, 0x21, 0x39, 0x37, 0xa4, 0xdb, 0x5b, 0xb9, 0x63, 0x36, 0xb8, 0x84, 0x91,
	0xb7, 0xc6, 0xb3, 0xdd, 0x28, 0xee, 0x65, 0xa7, 0x93, 0xff, 0x13, 0xc6, 0x7b, 0xeb, 0xa1, 0x5b,
	0x5c, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x5f, 0x76, 0xf6, 0xa9, 0x01, 0x00, 0x00,
}
